trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - dev
      - shreyasg/release-tag #release
pr:
  branches:
    include:
      - dev
      - master


jobs:
  - job: "Build_And_Test_Java_Library_Windows"
    pool:
      name: '1ES-Hosted-AzFunc'
      demands:
        - ImageOverride -equals MMS2019TLS

    steps:
    - task: NuGetToolInstaller@1
      inputs:
        checkLatest: true
    - pwsh: |
        Write-Host "Java_HOME: $JAVA_HOME"
        Get-Command mvn
      displayName: 'Check Maven is installed'
    - pwsh: '& .\build.ps1'

  - job: "Upload Jar to Release container"
    pool:
      name: '1ES-Hosted-AzFunc'
      demands:
        - ImageOverride -equals MMS2019TLS

    steps:
      - task: CmdLine@2
        displayName: Az Copy
        inputs:
          inlineScript: |
            echo "Hello world"