jobs:
  - job: "Build"
    displayName: 'Build java core library'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022 
      os: windows

    steps:
    - task: JavaToolInstaller@0 # This step is necessary as Linux image has Java 11 as default
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
      displayName: 'Setup Java for Linux'
    - pwsh: |
        Write-Host "Java_HOME: $JAVA_HOME"
        Get-Command mvn
      displayName: 'Check Maven is installed'
    - pwsh: '& .\build.ps1'
      displayName: 'Build project with java core library'