jobs:
  - job: "Build"
    displayName: 'Build java core library'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022 
      os: windows

    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
      displayName: 'Setup Java 11'
    - pwsh: |
        Write-Host "Java_HOME: $JAVA_HOME"
        Get-Command mvn
      displayName: 'Check Maven is installed'
    - pwsh: '& .\build.ps1'
      displayName: 'Build Java 11 libraries'
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
      displayName: 'Setup Java 17'
    - pwsh: |
        cd azure-functions-java-mcp
        mvn clean install "-Dgpg.skip=true" -B
      displayName: 'Build Java 17 libraries'
